name: Java CI

on: [push, pull_request]

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build with Gradle
        run: ./gradlew build --info --stacktrace --parallel
